server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manas
    username: postgres
    password: manas_team
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true

job:
  offer-constructor:
    enabled: true
    cron: ${CRON:0/10 * * * * *}
